[workspace]
authors = ["s0288 <alex.gansmann@hey.com>"]
channels = ["conda-forge"]
name = "loan_app"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
django = ">=5.2.7,<6"
python = ">=3.14.0,<3.15"
requests = ">=2.31.0"
