[workspace]
authors = ["s0288 <alex.gansmann@hey.com>"]
channels = ["conda-forge"]
name = "loan_app"
platforms = ["linux-64"]
version = "0.1.0"

[environments]
default = []
dev = ["default", "dev"]

[tasks]
docker-create-network = "docker network create loan-net"
docker-build = "docker build -t loan_app ."
docker-run = "docker run --rm --name loan_app --net loan-net --privileged -p 8001:8001 loan_app"

[dependencies]
django = ">=5.2.7,<6"
python = ">=3.14.0,<3.15"
requests = ">=2.31.0"

[feature.dev.tasks]
test-deploy = "python loan_app/manage.py runserver 0.0.0.0:8001"

